name: exam_feed
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  any_link_preview: ^3.0.2
  copy_file_to_clipboard: ^1.0.0
  dio: ^5.7.0
  easy_refresh: ^3.4.0
  envied: ^0.5.4+1
  extended_image: ^8.3.1
  file_picker: ^8.1.2
  firebase_analytics: ^11.3.3
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_messaging: ^15.1.3
  firebase_performance_dio: ^0.7.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_local_notifications: ^17.2.3
  flutter_screenutil: ^5.9.3
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  form_validator: ^2.1.1
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  go_router: ^14.2.8
  go_router_paths: ^0.2.2
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  json_serializable: ^6.8.0
  overlay_support: ^2.1.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.2
  readmore: ^3.0.0
  shared_preferences: ^2.3.2
  skeletonizer: ^1.4.2
  smooth_page_indicator: ^1.2.0+3
  spider: ^4.2.2
  timeago: ^3.7.0
  toastification: ^2.3.0
  url_launcher: ^6.3.0


dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  envied_generator: ^0.5.4+1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/env/

  # fonts:
  #   - family: Sora
  #     fonts:
  #       - asset: assets/fonts/Sora-Bold.ttf
  #       - asset: assets/fonts/Sora-ExtraBold.ttf
  #       - asset: assets/fonts/Sora-ExtraLight.ttf
  #       - asset: assets/fonts/Sora-Light.ttf
  #       - asset: assets/fonts/Sora-Regular.ttf
  #       - asset: assets/fonts/Sora-SemiBold.ttf
  #       - asset: assets/fonts/Sora-Thin.ttf
